site_name: Lepo
pages:
- index.md
- features.md
- getting-started.md
- class-based-handlers.md
- concepts.md
theme: material
markdown_extensions:
- admonition
- codehilite
- pymdownx.tasklist(custom_checkbox=true)
- pymdownx.inlinehilite
extra:
  palette:
    primary: 'deep purple'
    accent: 'indigo'
repo_name: 'akx/lepo'
repo_url: 'https://github.com/akx/lepo'
copyright: 'Copyright &copy; 2017 Lepo authors'
